# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67c95dcc6060ef1f4a20a50a4ede66cc344c17790b465779bdd3174bd8718b460f9bf8e0c6990b822db69284a516e34d8af89834c2388d5dfb0ad729607fd3ea

test:
  secret_key_base: 92f793345fbda2e0f8830def092cebfb75ca6188a8251ca274cbcc5ba035b9620effde893f256bbe4e211a02c0c6a6ec7268a14bb1f71e53dac6f0ae6a311d7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
